name: Test All
on:
  push:
    paths:
      - '**.kt'
      - '**.rs'
      - 'gradle/libs.versions.toml'
      - '**.kts'
      - '**.xml'
      - '**.jar'
      - '**.properties'
      - 'incus/intervirt-os.yaml'

jobs:
  test:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - name: Install Rust dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev pkg-config libwebkit2gtk-4.1-dev -y
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
      - name: Test Core
        run: ./gradlew :core:allTests
      - name: Test UI
        run: ./gradlew :ui:allTests
      - name: Test Secret
        run: ./gradlew :secret:test
      - name: Test Logging
        run: ./gradlew :logging:allTests
